from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(907, 637)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.mainWidget = QtWidgets.QWidget(MainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(658, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.mainWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.mainWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.sectionWidget = QtWidgets.QWidget()
        self.sectionWidget.setObjectName("sectionWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sectionWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.sectionWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sort_b_2 = QtWidgets.QPushButton(self.sectionWidget)
        self.sort_b_2.setObjectName("sort_b_2")
        self.horizontalLayout_3.addWidget(self.sort_b_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.open_b_2 = QtWidgets.QPushButton(self.sectionWidget)
        self.open_b_2.setObjectName("open_b_2")
        self.horizontalLayout_4.addWidget(self.open_b_2)
        self.change_b_2 = QtWidgets.QPushButton(self.sectionWidget)
        self.change_b_2.setObjectName("change_b_2")
        self.horizontalLayout_4.addWidget(self.change_b_2)
        self.del_b_2 = QtWidgets.QPushButton(self.sectionWidget)
        self.del_b_2.setObjectName("del_b_2")
        self.horizontalLayout_4.addWidget(self.del_b_2)
        self.add_b_2 = QtWidgets.QPushButton(self.sectionWidget)
        self.add_b_2.setObjectName("add_b_2")
        self.horizontalLayout_4.addWidget(self.add_b_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.sectionWidget, "")
        self.recordWidget = QtWidgets.QWidget()
        self.recordWidget.setObjectName("recordWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.recordWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.recordWidget)
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(0)
        self.tableWidget_1.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sort_b_1 = QtWidgets.QPushButton(self.recordWidget)
        self.sort_b_1.setObjectName("sort_b_1")
        self.horizontalLayout_2.addWidget(self.sort_b_1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.open_b_1 = QtWidgets.QPushButton(self.recordWidget)
        self.open_b_1.setObjectName("open_b_1")
        self.horizontalLayout_1.addWidget(self.open_b_1)
        self.change_b_1 = QtWidgets.QPushButton(self.recordWidget)
        self.change_b_1.setObjectName("change_b_1")
        self.horizontalLayout_1.addWidget(self.change_b_1)
        self.del_b_1 = QtWidgets.QPushButton(self.recordWidget)
        self.del_b_1.setObjectName("del_b_1")
        self.horizontalLayout_1.addWidget(self.del_b_1)
        self.add_b_1 = QtWidgets.QPushButton(self.recordWidget)
        self.add_b_1.setObjectName("add_b_1")
        self.horizontalLayout_1.addWidget(self.add_b_1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.recordWidget, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Настройки"))
        self.sort_b_2.setText(_translate("MainWindow", "Отсортировать"))
        self.open_b_2.setText(_translate("MainWindow", "Открыть"))
        self.change_b_2.setText(_translate("MainWindow", "Изменить"))
        self.del_b_2.setText(_translate("MainWindow", "Удалить"))
        self.add_b_2.setText(_translate("MainWindow", "Новая папка"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sectionWidget), _translate("MainWindow", "Папки"))
        self.sort_b_1.setText(_translate("MainWindow", "Отсортировать"))
        self.open_b_1.setText(_translate("MainWindow", "Открыть"))
        self.change_b_1.setText(_translate("MainWindow", "Изменить"))
        self.del_b_1.setText(_translate("MainWindow", "Удалить"))
        self.add_b_1.setText(_translate("MainWindow", "Новая запись"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recordWidget), _translate("MainWindow", "Все записи"))
