from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 625)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.mainWidget = QtWidgets.QWidget(MainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.mainWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 791, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.sectionWidget = QtWidgets.QWidget()
        self.sectionWidget.setObjectName("sectionWidget")
        self.tableWidget = QtWidgets.QTableWidget(self.sectionWidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 761, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.layoutWidget_2 = QtWidgets.QWidget(self.sectionWidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 510, 761, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sort_b_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.sort_b_2.setObjectName("sort_b_2")
        self.horizontalLayout_3.addWidget(self.sort_b_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.open_b_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.open_b_2.setObjectName("open_b_2")
        self.horizontalLayout_4.addWidget(self.open_b_2)
        self.change_b_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.change_b_2.setObjectName("change_b_2")
        self.horizontalLayout_4.addWidget(self.change_b_2)
        self.del_b_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.del_b_2.setObjectName("del_b_2")
        self.horizontalLayout_4.addWidget(self.del_b_2)
        self.add_b_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.add_b_2.setObjectName("add_b_2")
        self.horizontalLayout_4.addWidget(self.add_b_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.sectionWidget, "")
        self.recordWidget = QtWidgets.QWidget()
        self.recordWidget.setObjectName("recordWidget")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.recordWidget)
        self.tableWidget_1.setGeometry(QtCore.QRect(10, 10, 761, 481))
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(0)
        self.tableWidget_1.setRowCount(0)
        self.widget = QtWidgets.QWidget(self.recordWidget)
        self.widget.setGeometry(QtCore.QRect(10, 510, 761, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sort_b_1 = QtWidgets.QPushButton(self.widget)
        self.sort_b_1.setObjectName("sort_b_1")
        self.horizontalLayout_2.addWidget(self.sort_b_1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.open_b_1 = QtWidgets.QPushButton(self.widget)
        self.open_b_1.setObjectName("open_b_1")
        self.horizontalLayout_1.addWidget(self.open_b_1)
        self.change_b_1 = QtWidgets.QPushButton(self.widget)
        self.change_b_1.setObjectName("change_b_1")
        self.horizontalLayout_1.addWidget(self.change_b_1)
        self.del_b_1 = QtWidgets.QPushButton(self.widget)
        self.del_b_1.setObjectName("del_b_1")
        self.horizontalLayout_1.addWidget(self.del_b_1)
        self.add_b_1 = QtWidgets.QPushButton(self.widget)
        self.add_b_1.setObjectName("add_b_1")
        self.horizontalLayout_1.addWidget(self.add_b_1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_1)
        self.tabWidget.addTab(self.recordWidget, "")
        self.sittings_b = QtWidgets.QPushButton(self.mainWidget)
        self.sittings_b.setGeometry(QtCore.QRect(710, 10, 75, 23))
        self.sittings_b.setObjectName("sittings_b")
        MainWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sort_b_2.setText(_translate("MainWindow", "Отсортировать"))
        self.open_b_2.setText(_translate("MainWindow", "Открыть"))
        self.change_b_2.setText(_translate("MainWindow", "Изменить"))
        self.del_b_2.setText(_translate("MainWindow", "Удалить"))
        self.add_b_2.setText(_translate("MainWindow", "Новый раздел"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sectionWidget), _translate("MainWindow", "Раздел"))
        self.sort_b_1.setText(_translate("MainWindow", "Отсортировать"))
        self.open_b_1.setText(_translate("MainWindow", "Открыть"))
        self.change_b_1.setText(_translate("MainWindow", "Изменить"))
        self.del_b_1.setText(_translate("MainWindow", "Удалить"))
        self.add_b_1.setText(_translate("MainWindow", "Новая запись"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recordWidget), _translate("MainWindow", "Записи"))
        self.sittings_b.setText(_translate("MainWindow", "Настройки"))
